fridge_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 40.0, i: 0.01, d: 2}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 40.0, i: 0.01, d: 2}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: {p: 40.0, i: 0.01, d: 2}

  # Effort Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint1
  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint3
  joint7_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint7